### PR TITLE
Lock lowdb file

### PR DESCRIPTION
**Pull request by MGibson1**
# Overview

Linked to #41 
Related to jslib PR bitwarden/jslib#273

Changes lowdb storage service to use nocache and require file locks on all db access operations.

#### Fixes linter globbing issues

# Files Changed

* **Package.json/package-lock.json**: Add proper-lockfile depenendency
* **bwdc.ts**: Change allowcache to false and requireLock to true

other changes are linter fixes

# Draft reason

Depends on bitwarden/jslib#273

### CODE REVIEW

**Review by cscharf — COMMENTED** [review]
I think will look okay once jslib passes build + merge.

**Comment by MGibson1** [comment]
It turns out proper-lockfile is incompatible with non-node builds so it can't go in jslib.

I've moved the dependency to this repository in a subclass.

**Comment by cscharf** [comment]
```
Run Expand-Archive -Path "./dist-cli/bwdc-windows-${env:PACKAGE_VERSION}.zip" -DestinationPath "./test/windows"
Could not find dir, "C:\Users\runneradmin\AppData\Roaming\Bitwarden Directory Connector"; creating it instead.
(node:2180) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'C:\Users\runneradmin\AppData\Roaming\Bitwarden Directory Connector\data.json'
(node:2180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
version: 2.9.0
testVersion: 
Exception: D:\a\_temp\fb89fe20-b67b-4c8c-a596-398223529ccf.ps1:7
Line |
   7 |    Throw "Version test failed."
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Version test failed.
```

**Comment by MGibson1** [comment]
Just asked @joseph-flinn about the secret/decrypt failures. Not sure what the versioning issue is either :(

**Comment by cscharf** [comment]
One more test error:
```
Run Expand-Archive -Path "./dist-cli/bwdc-windows-${env:PACKAGE_VERSION}.zip" -DestinationPath "./test/windows"
Could not find data file, "undefined"; creating it instead.
(node:6880) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.fs.openSync (fs.js:572:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:483:32)
    at Object.fs.writeFileSync (fs.js:1309:33)
    at services_lowdbStorage_service_LowdbStorageService.<anonymous> (D:\snapshot\directory-connector\build-cli\bwdc.js:1656:46)
    at Generator.next (<anonymous>)
    at services_lowdbStorage_service_awaiter (D:\snapshot\directory-connector\build-cli\bwdc.js:1637:71)
    at new Promise (<anonymous>)
    at services_lowdbStorage_service_awaiter (D:\snapshot\directory-connector\build-cli\bwdc.js:1633:12)
    at services_lowdbStorage_service_LowdbStorageService.init (D:\snapshot\directory-connector\build-cli\bwdc.js:1653:16)
    at bwdc_Main.<anonymous> (D:\snapshot\directory-connector\build-cli\bwdc.js:17864:39)
(node:6880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
version: 2.9.0
testVersion: 
Exception: D:\a\_temp\79c98d64-2d69-4d53-ad65-3cb620f100bd.ps1:7
Line |
   7 |    Throw "Version test failed."
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Version test failed.

Error: Process completed with exit code 1.
```

**Comment by MGibson1** [comment]
the last CI issue is proper-lockfile throwing up because of the database file not existing prior to locking. I need to change this in jslib :( writing a PR now.

**Comment by MGibson1** [comment]
bitwarden/jslib#274

**Review by cscharf — APPROVED** [review]
Yay!

**Comment by MGibson1** [comment]
lol, I know. Thanks for sticking through this with me

**Pull request merged**
